// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/3/2026, 4:08:58 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/SDL/nest.js/laoshop/full-stack-web-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/SDL/nest.js/laoshop/full-stack-web-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/SDL/nest.js/laoshop/full-stack-web-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/SDL/nest.js/laoshop/full-stack-web-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/SDL/nest.js/laoshop/full-stack-web-nuxt/plugins/**/*.{js,ts,mjs}","C:/SDL/nest.js/laoshop/full-stack-web-nuxt/composables/**/*.{js,ts,mjs}","C:/SDL/nest.js/laoshop/full-stack-web-nuxt/utils/**/*.{js,ts,mjs}","C:/SDL/nest.js/laoshop/full-stack-web-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/SDL/nest.js/laoshop/full-stack-web-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/SDL/nest.js/laoshop/full-stack-web-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/SDL/nest.js/laoshop/full-stack-web-nuxt/app.config.{js,ts,mjs}","C:/SDL/nest.js/laoshop/full-stack-web-nuxt/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;